---

services:
  CopypartyTunnel:
    image: cloudflare/cloudflared:latest
    container_name: CPTunnel  
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    restart: unless-stopped


  copyparty:
    image: copyparty/ac:latest
    container_name: copyparty
    restart: unless-stopped
    depends_on:
      - CopypartyTunnel
    user: "1000:1000"
    ports:
      - 3923:3923
    volumes:
      - ./:/cfg:z
      - ./data:/data:z
    environment:
      LD_PRELOAD: /usr/lib/libmimalloc-secure.so.2
      # enable mimalloc by replacing "NOPE" with "2" for a nice speed-boost (will use twice as much ram)
      PYTHONUNBUFFERED: 1

  gitea:
    image: docker.gitea.com/gitea:1.25.4-rootless
    restart: always
    volumes:
      - ./data/gitea:/var/lib/gitea
      - ./:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"

  homeassistant:
    image: homeassistant/home-assistant:latest
    container_name: homeassistant
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data/homeassistant:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/Los_Angeles